export const VIETNAM_PROVINCES = [
    // 6 thành phố trực thuộc Trung ương
    'Hà Nội',
    'Hải Phòng',
    'Huế',
    'Đà Nẵng',
    'Cần Thơ',
    'TP. Hồ Chí Minh',
    // 28 tỉnh
    'Cao Bằng',
    'Lai Châu',
    'Điện Biên',
    'Sơn La',
    'Lạng Sơn',
    'Quảng Ninh',
    'Tuyên Quang',
    'Lào Cai',
    'Thái Nguyên',
    'Phú Thọ',
    'Bắc Ninh',
    'Hưng Yên',
    'Ninh Bình',
    'Thanh Hóa',
    'Nghệ An',
    'Hà Tĩnh',
    'Quảng Trị',
    'Quảng Ngãi',
    'Gia Lai',
    'Khánh Hòa',
    'Lâm Đồng',
    'Đắk Lắk',
    'Đồng Nai',
    'Tây Ninh',
    'Đồng Tháp',
    'Vĩnh Long',
    'An Giang',
    'Cà Mau'
];
